//
//  DataSourcesView.swift
//  LaborForecast
//
//  Created by Josue Cruz on 3/15/26.
//

import SwiftUI

struct DataSourcesView: View {
    
    var body: some View {
        List {
            Section("Labor Market Data") {
                VStack(alignment: .leading, spacing: 6) {
                    Text("Bureau of Labor Statistics")
                        .font(.subheadline)
                        .fontWeight(.semibold)
                    Text("Occupational Outlook Handbook, 2024–2034 projections. Employment counts, median salaries, education requirements, and 10-year growth projections.")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    Link("bls.gov/ooh", destination: URL(string: "https://www.bls.gov/ooh")!)
                        .font(.caption)
                        .foregroundStyle(Color.LFGreen)
                }
                .padding(.vertical, 4)
            }

            Section("AI Exposure Scoring") {
                VStack(alignment: .leading, spacing: 6) {
                    Text("Gemini Flash — Structured Rubric")
                        .font(.subheadline)
                        .fontWeight(.semibold)
                    Text("AI exposure scores (0–10) were generated using Google Gemini Flash with a structured rubric developed by Andrej Karpathy. The key signal: whether a job's work product is fundamentally digital. Jobs done entirely on a computer score higher; jobs requiring physical presence or manual skill score lower.")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
                .padding(.vertical, 4)
            }

            Section("Acknowledgements") {
                VStack(alignment: .leading, spacing: 6) {
                    Text("Andrej Karpathy")
                        .font(.subheadline)
                        .fontWeight(.semibold)
                    Text("AI exposure scoring concept and pipeline. Karpathy designed the 0–10 scoring rubric, scraped all 342 BLS occupations, and built the original LLM scoring pipeline that this app's data is built upon. This app includes 341 of those occupations.")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    Link("@karpathy on X", destination: URL(string: "https://x.com/karpathy")!)
                        .font(.caption)
                        .foregroundStyle(Color.LFGreen)
                }
                .padding(.vertical, 4)
            }

            Section("Disclaimer") {
                Text("AI exposure scores are estimates generated by a language model using a structured rubric. They reflect general patterns in occupational tasks and should not be interpreted as precise predictions. Karpathy himself noted this was an exploratory project and cautioned against overinterpretation. Use these scores as a starting point for career research, not as a definitive forecast.")
                    .font(.caption)
                    .foregroundStyle(.secondary)
                    .padding(.vertical, 4)
            }
        }
        .navigationTitle("Data Sources")
        .navigationBarTitleDisplayMode(.large)
    }
}
